matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    services:
    - docker
    script:
    - docker run --rm -v ${PWD}:/project -e GH_TOKEN=${GH_TOKEN} -e TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST} rocketchat/electron.builder /bin/bash -l -c "npm install && npm run release -- --x64 --ia32"
  - os: osx
    osx_image: xcode7.3.1
    language: generic
    node_js:
    - '6'
    before_script:
    - chmod +x ./scripts/travis-build.sh
    script: ./scripts/travis-build.sh
    cache:
      directories:
        - node_modules

branches:
  only:
    - master
    - develop

notifications:
  email:
    on_success: never
    on_failure: change
